In [1]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.read_csv('amazon.csv')

In [3]:
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   str
 1   product_name         1465 non-null   str
 2   category             1465 non-null   str
 3   discounted_price     1465 non-null   str
 4   actual_price         1465 non-null   str
 5   discount_percentage  1465 non-null   str
 6   rating               1465 non-null   str
 7   rating_count         1463 non-null   str
 8   about_product        1465 non-null   str
 9   user_id              1465 non-null   str
 10  user_name            1465 non-null   str
 11  review_id            1465 non-null   str
 12  review_title         1465 non-null   str
 13  review_content       1465 non-null   str
 14  img_link             1465 non-null   str
 15  product_link         1465 non-null   str
dtypes: str(16)
memory usage: 4.7 MB

In [5]:
#product_id,product_name,category,rating,rating_count,about_product,review_title,review_content,img_link

In [6]:
df['product_link'][0]

'https://www.amazon.in/Wayona-Braided-WN3LG1-Syncing-Charging/dp/B07JW9H4J1/ref=sr_1_1?qid=1672909124&s=electronics&sr=1-1'

In [7]:
df['product_name'][0]

'Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)'

In [8]:
df['category'][0].split('|')

['Computers&Accessories',
 'Accessories&Peripherals',
 'Cables&Accessories',
 'Cables',
 'USBCables']

In [9]:
df.groupby('product_id')['product_name'].count()

product_id
B002PD61Y4    2
B002SZEOLG    1
B003B00484    1
B003L62T7W    1
B004IO5BMQ    1
             ..
B0BPCJM7TB    1
B0BPJBTB3F    1
B0BQ3K23Y1    1
B0BQRJ3C47    1
B0BR4F878Q    1
Name: product_name, Length: 1351, dtype: int64

In [10]:
data = df[['product_id','product_name','category','rating','rating_count','about_product','review_title','review_content','img_link']]

In [11]:
data.head(1)

,product_id,product_name,category,rating,rating_count,about_product,review_title,review_content,img_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...

In [12]:
from nltk.corpus import stopwords

In [13]:
import string
stopwords = stopwords.words('english')
def remove_punctuations(text):

    return text.translate(str.maketrans('', '', string.punctuation))
def remove_stopwords(text):
    l = []
    for i in text.split():
        if i not in stopwords:
            l.append(i)
    return " ".join(l)

In [14]:
remove_stopwords(data['product_name'][0])

'Wayona Nylon Braided USB Lightning Fast Charging Data Sync Cable Compatible iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack 1, Grey)'

In [15]:
data['product_name']=data['product_name'].apply(remove_punctuations)
data['product_name'] = data['product_name'].apply(remove_stopwords)

In [16]:
df['product_name'][0]

'Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)'

In [17]:
data['product_name'][0]

'Wayona Nylon Braided USB Lightning Fast Charging Data Sync Cable Compatible iPhone 13 1211 X 8 7 6 5 iPad Air Pro Mini 3 FT Pack 1 Grey'

In [18]:
df.shape

(1465, 16)

In [19]:
df.isna().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [20]:
data['review_content'][0]

'Looks durable Charging is fine tooNo complains,Charging is really fast, good product.,Till now satisfied with the quality.,This is a good product . The charging speed is slower than the original iPhone cable,Good quality, would recommend,https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81---F1ZgHL._SY88.jpg,Product had worked well till date and was having no issue.Cable is also sturdy enough...Have asked for replacement and company is doing the same...,Value for money'

In [21]:
import re
pattern = re.compile('https.*.?.jpg')
pattern.sub(r'',data['review_content'][0])

'Looks durable Charging is fine tooNo complains,Charging is really fast, good product.,Till now satisfied with the quality.,This is a good product . The charging speed is slower than the original iPhone cable,Good quality, would recommend,,Product had worked well till date and was having no issue.Cable is also sturdy enough...Have asked for replacement and company is doing the same...,Value for money'

In [22]:
def remove_url(text):
    pattern = re.compile('https.*.?.jpg')
    return pattern.sub(r'',text)

In [23]:
remove_url(df['review_content'][0])

'Looks durable Charging is fine tooNo complains,Charging is really fast, good product.,Till now satisfied with the quality.,This is a good product . The charging speed is slower than the original iPhone cable,Good quality, would recommend,,Product had worked well till date and was having no issue.Cable is also sturdy enough...Have asked for replacement and company is doing the same...,Value for money'

In [24]:
data['review_content']=data['review_content'].apply(remove_url)

In [25]:
data['review_content'][1000]

'Packing is good .. they have sent a box for itAlso the quality looks good and decently fast chargingGood product for the price paid,Nice product,nice charging cable for low cost.,Highly recommended,Quite nice cable in this price, charging my iPad smoothly  Go for it,I like the product and resnable precise.,Worth buyinh,Nice'

In [26]:
df['review_content'][1110]

'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/61EIm64sN-L._SY88.jpg,https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/611OwR2Z7kL._SY88.jpg,Cord length very smallPlease add longer cord,Product is good temperatures control is also good I used around 1 month  you can go for it but keep in mind that cord length is short,,Product is good, but power cable is less than 30 cm in length. so, difficult to use it.,,Tea/coffee'

In [27]:
data['review_content'][1110]

',Cord length very smallPlease add longer cord,Product is good temperatures control is also good I used around 1 month  you can go for it but keep in mind that cord length is short,,Product is good, but power cable is less than 30 cm in length. so, difficult to use it.,,Tea/coffee'

In [28]:
data['review_content'] = data['review_content'].apply(remove_punctuations)
data['review_content'] = data['review_content'].apply(remove_stopwords)

In [29]:
df['review_content'][1110]

'https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/61EIm64sN-L._SY88.jpg,https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/611OwR2Z7kL._SY88.jpg,Cord length very smallPlease add longer cord,Product is good temperatures control is also good I used around 1 month  you can go for it but keep in mind that cord length is short,,Product is good, but power cable is less than 30 cm in length. so, difficult to use it.,,Tea/coffee'

In [30]:
data['review_content'][1110]

'Cord length smallPlease add longer cordProduct good temperatures control also good I used around 1 month go keep mind cord length shortProduct good power cable less 30 cm length difficult use itTeacoffee'

In [31]:
from nltk.stem import PorterStemmer
porter_stemmer = PorterStemmer()

def apply_stemming(text):
    l = []
    for i in text.split():
        l.append(porter_stemmer.stem(i))
    return " ".join(l)

In [32]:
apply_stemming(data['review_content'][1110])

'cord length smallpleas add longer cordproduct good temperatur control also good i use around 1 month go keep mind cord length shortproduct good power cabl less 30 cm length difficult use itteacoffe'

In [33]:
data['review_content'] = data['review_content'].apply(apply_stemming)

In [34]:
data['review_title'][0]

'Satisfied,Charging is really fast,Value for money,Product review,Good quality,Good product,Good Product,As of now seems good'

In [35]:
data['review_title'] = data['review_title'].apply(remove_stopwords)
data['review_title'] = data['review_title'].apply(remove_punctuations)
data['review_title'] = data['review_title'].apply(apply_stemming)

In [36]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      1465 non-null   str
 1   product_name    1465 non-null   str
 2   category        1465 non-null   str
 3   rating          1465 non-null   str
 4   rating_count    1463 non-null   str
 5   about_product   1465 non-null   str
 6   review_title    1465 non-null   str
 7   review_content  1465 non-null   str
 8   img_link        1465 non-null   str
dtypes: str(9)
memory usage: 3.0 MB

In [37]:
data['about_product'] = data['about_product'].apply(remove_stopwords)
data['about_product'] = data['about_product'].apply(remove_punctuations)
data['about_product'] = data['about_product'].apply(apply_stemming)

In [38]:
data['product_name'] = data['product_name'].apply(remove_stopwords)
data['product_name'] = data['product_name'].apply(remove_punctuations)
data['product_name'] = data['product_name'].apply(apply_stemming)

In [39]:
data.head()

,product_id,product_name,category,rating,rating_count,about_product,review_title,review_content,img_link
0,B07JW9H4J1,wayona nylon braid usb lightn fast charg data ...,Computers&Accessories|Accessories&Peripherals|...,4.2,"24,269",high compat compat with iphon 12 11 xxsmaxxr i...,satisfiedcharg realli fastvalu moneyproduct re...,look durabl charg fine toono complainscharg re...,https://m.media-amazon.com/images/W/WEBP_40237...
1,B098NS6PVG,ambran unbreak 60w 3a fast charg 15m braid typ...,Computers&Accessories|Accessories&Peripherals|...,4.0,"43,994",compat type c enabl devic android smartphon mi...,a good braid cabl your type c devicegood quali...,i order cabl connect phone android auto car th...,https://m.media-amazon.com/images/W/WEBP_40237...
2,B096MSW6CT,sounc fast phone charg cabl data sync usb cabl...,Computers&Accessories|Accessories&Peripherals|...,3.9,"7,928",【 fast charger data sync】with builtin safeti p...,good speed earlier versionsgood productwork go...,not quit durabl sturdyproductveri nice product...,https://m.media-amazon.com/images/W/WEBP_40237...
3,B08HDJ86NZ,boat deuc usb 300 2 1 typec micro usb stress r...,Computers&Accessories|Accessories&Peripherals|...,4.2,"94,363",the boat deuc usb 300 2 1 cabl compat smartpho...,good productgood onenicer nice productveri fir...,good productlong wirecharg goodnicei bought ca...,https://m.media-amazon.com/images/I/41V5FtEWPk...
4,B08CF3B7N1,portron konnect l 12m fast charg 3a 8 pin usb ...,Computers&Accessories|Accessories&Peripherals|...,4.2,"16,905",charg sync function thi cabl come charg data s...,as good originaldecentgood one secondari usebe...,bought instead origin appl work 150r fast appl...,https://m.media-amazon.com/images/W/WEBP_40237...

In [40]:
def sep_category(text):
    l = []
    for i in text.split('|'):
        l.append(i.lower())
    return " ".join(l)

In [41]:
sep_category(data['category'][0])

'computers&accessories accessories&peripherals cables&accessories cables usbcables'

In [42]:
data['category'] = data['category'].apply(sep_category)
data['category'] = data['category'].apply(apply_stemming)

In [43]:
data['product_detail'] = data['category'] + data['product_name'] + data['about_product']
data['review'] = data['review_title'] + data['review_content']

In [44]:
data

,product_id,product_name,category,rating,rating_count,about_product,review_title,review_content,img_link,product_detail,review
0,B07JW9H4J1,wayona nylon braid usb lightn fast charg data ...,computers&accessori accessories&peripher cable...,4.2,"24,269",high compat compat with iphon 12 11 xxsmaxxr i...,satisfiedcharg realli fastvalu moneyproduct re...,look durabl charg fine toono complainscharg re...,https://m.media-amazon.com/images/W/WEBP_40237...,computers&accessori accessories&peripher cable...,satisfiedcharg realli fastvalu moneyproduct re...
1,B098NS6PVG,ambran unbreak 60w 3a fast charg 15m braid typ...,computers&accessori accessories&peripher cable...,4.0,"43,994",compat type c enabl devic android smartphon mi...,a good braid cabl your type c devicegood quali...,i order cabl connect phone android auto car th...,https://m.media-amazon.com/images/W/WEBP_40237...,computers&accessori accessories&peripher cable...,a good braid cabl your type c devicegood quali...
2,B096MSW6CT,sounc fast phone charg cabl data sync usb cabl...,computers&accessori accessories&peripher cable...,3.9,"7,928",【 fast charger data sync】with builtin safeti p...,good speed earlier versionsgood productwork go...,not quit durabl sturdyproductveri nice product...,https://m.media-amazon.com/images/W/WEBP_40237...,computers&accessori accessories&peripher cable...,good speed earlier versionsgood productwork go...
3,B08HDJ86NZ,boat deuc usb 300 2 1 typec micro usb stress r...,computers&accessori accessories&peripher cable...,4.2,"94,363",the boat deuc usb 300 2 1 cabl compat smartpho...,good productgood onenicer nice productveri fir...,good productlong wirecharg goodnicei bought ca...,https://m.media-amazon.com/images/I/41V5FtEWPk...,computers&accessori accessories&peripher cable...,good productgood onenicer nice productveri fir...
4,B08CF3B7N1,portron konnect l 12m fast charg 3a 8 pin usb ...,computers&accessori accessories&peripher cable...,4.2,"16,905",charg sync function thi cabl come charg data s...,as good originaldecentgood one secondari usebe...,bought instead origin appl work 150r fast appl...,https://m.media-amazon.com/images/W/WEBP_40237...,computers&accessori accessories&peripher cable...,as good originaldecentgood one secondari usebe...
...,...,...,...,...,...,...,...,...,...,...,...
1460,B08L7J3T31,noir aqua 5pc pp spun filter 1 spanner all typ...,home&kitchen kitchen&homeappli waterpurifiers&...,4,"1,090",suprem qualiti 90 gram 3 layer thik pp spun fi...,receiv product without spannerexcel productsat...,i receiv product without spannerexcel producti...,https://m.media-amazon.com/images/I/41fDdRtjfx...,home&kitchen kitchen&homeappli waterpurifiers&...,receiv product without spannerexcel productsat...
1461,B01M6453MB,prestig delight prwo electr rice cooker 1 l white,home&kitchen kitchen&homeappli smallkitchenapp...,4.1,"4,118",230 volt 400 watt 1 year,okeveryth good return bcoz i need emergencydon...,okgot everyth mention measur cup broken didnt ...,https://m.media-amazon.com/images/I/41gzDxk4+k...,home&kitchen kitchen&homeappli smallkitchenapp...,okeveryth good return bcoz i need emergencydon...
1462,B009P2LIL4,bajaj majesti rx10 2000 watt heat convector ro...,"home&kitchen heating,cooling&airqu roomheat he...",3.6,468,intern design stylingtwo heat set 1000 w 2000 ...,goodwork front melt 2 monthgood oneit durabler...,plastic cool bodi u find sturdi surfac put ver...,https://m.media-amazon.com/images/W/WEBP_40237...,"home&kitchen heating,cooling&airqu roomheat he...",goodwork front melt 2 monthgood oneit durabler...
1463,B00J5DYCCA,havel ventil air dsp 230mm exhaust fan pista g...,"home&kitchen heating,cooling&airqu fan exhaustfan",4,"8,031",fan sweep area 230 mm nois level 40 45 db fan ...,fan speed slowgood qualitygood productgoodold ...,i instal kitchen work fine fan speed slow coul...,https://m.media-amazon.com/images/W/WEBP_40237...,"home&kitchen heating,cooling&airqu fan exhaust...",fan speed slowgood qualitygood productgoodold ...
1464,B01486F4G6,borosil jumbo 1000watt grill sandwich maker black,home&kitchen kitchen&homeappli smallkitchenapp...,4.3,"6,987",brandborosil specif â€“ 23v 5hz1 w power faste...,work perfectok good productnic product recomme...,it job perfectlyonli issu temp control perfect...,https://m.media-amazon.com/images/W/WEBP_40237...,home&kitchen kitchen&homeappli smallkitchenapp...,work perfectok good productnic product recomme...

In [45]:
from nltk.tokenize import sent_tokenize

In [46]:
new_data = data[['review','product_detail']]

In [47]:
new_data.iloc[0]

review            satisfiedcharg realli fastvalu moneyproduct re...
product_detail    computers&accessori accessories&peripher cable...
Name: 0, dtype: str

In [48]:
sent_tokenize('satisfiedcharg realli fastvalu moneyproduct')

['satisfiedcharg realli fastvalu moneyproduct']

In [49]:
def tokenize(text):
    return sent_tokenize(text)

In [50]:
data['review'] = data['review'].apply(tokenize)
data['product_detail'] = data['product_detail'].apply(tokenize)

In [51]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [52]:
tfidf = TfidfVectorizer()

In [53]:
data['product_detail']

0       [computers&accessori accessories&peripher cabl...
1       [computers&accessori accessories&peripher cabl...
2       [computers&accessori accessories&peripher cabl...
3       [computers&accessori accessories&peripher cabl...
4       [computers&accessori accessories&peripher cabl...
                              ...
1460    [home&kitchen kitchen&homeappli waterpurifiers...
1461    [home&kitchen kitchen&homeappli smallkitchenap...
1462    [home&kitchen heating,cooling&airqu roomheat h...
1463    [home&kitchen heating,cooling&airqu fan exhaus...
1464    [home&kitchen kitchen&homeappli smallkitchenap...
Name: product_detail, Length: 1465, dtype: object

In [54]:
data[['product_detail']]

                                         product_detail
0     [computers&accessori accessories&peripher cabl...
1     [computers&accessori accessories&peripher cabl...
2     [computers&accessori accessories&peripher cabl...
3     [computers&accessori accessories&peripher cabl...
4     [computers&accessori accessories&peripher cabl...
...                                                 ...
1460  [home&kitchen kitchen&homeappli waterpurifiers...
1461  [home&kitchen kitchen&homeappli smallkitchenap...
1462  [home&kitchen heating,cooling&airqu roomheat h...
1463  [home&kitchen heating,cooling&airqu fan exhaus...
1464  [home&kitchen kitchen&homeappli smallkitchenap...

[1465 rows x 1 columns]

In [55]:
all_sentences = []

for sentence_list in data['product_detail']:
    all_sentences.extend(sentence_list)

from sklearn.metrics.pairwise import cosine_similarity
tfidf_matrix = tfidf.fit_transform(all_sentences)

similarity = cosine_similarity(tfidf_matrix)

In [56]:
similarity.shape

(1465, 1465)

In [57]:
query = "Samsung tv"

# Transform the query (do NOT fit again)
query_vector = tfidf.transform([query])

# Compute similarities
scores = cosine_similarity(query_vector, tfidf_matrix)
sorted(enumerate(scores), key=lambda x:x[1])

[(0,
  array([0.        , 0.07046422, 0.        , ..., 0.        , 0.        ,
         0.        ], shape=(1465,)))]

In [58]:
df[df['product_id'] == 'B096MSW6CT']

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
379,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹999,80%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/I/31IvNJZnmd...,https://www.amazon.in/Sounce-iPhone-Charging-C...
623,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹999,80%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...

In [59]:
import numpy as np

top_indices = np.argsort(scores[0])[::-1][0:5]

for idx in top_indices:
    pid = data['product_id'][idx]
    d = df[df['product_id'] == str(pid)]
    print(d['product_name'])
    print('score =' ,scores[0][idx])

48    7SEVEN® Compatible for Samsung Smart 4K Ultra ...
Name: product_name, dtype: str
score = 0.5004115312614609
102    Isoelite Remote Compatible for Samsung LED/LCD...
Name: product_name, dtype: str
score = 0.45826586282620524
225    Remote Compatible for Samsung LED/LCD Remote C...
Name: product_name, dtype: str
score = 0.4145347549477044
298    PROLEGEND® PL-T002 Universal TV Stand Table To...
Name: product_name, dtype: str
score = 0.33199137692184527
165    LOHAYA Television Remote Compatible with Samsu...
Name: product_name, dtype: str
score = 0.3241023569715407

In [60]:
data['product_id'][2]

'B096MSW6CT'

In [61]:
np.argsort(scores[0])[::-1][0:5]

array([ 48, 102, 225, 298, 165])

In [62]:
scores[0]

array([0.        , 0.07046422, 0.        , ..., 0.        , 0.        ,
       0.        ], shape=(1465,))

In [63]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\HARSH\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [64]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()

In [65]:
def get_sentiment(text):
    return sia.polarity_scores(str(text))['compound']

In [66]:
get_sentiment('useful')

0.4404

In [67]:
data['sentiment'] = data['review'].apply(get_sentiment)

In [68]:
def recomend(text):
    text = str(text)
    input_vec = tfidf.transform([text])
    scores = cosine_similarity(input_vec, tfidf_matrix)
    scores = scores[0]*   (1 + data['sentiment'])
    idx = np.argsort(scores)[::-1][:5]
    return idx,scores
def get_product_name(idx):
    l = []
    for i in idx:
        pid = data['product_id'][i]
        d = df[df['product_id'] == str(pid)]
        l.append(d['product_name'])
    return l

In [69]:
idx,scores = recomend('HD tv')
get_product_name(idx)

[284    Tata Sky Digital TV HD Setup Box Remote
 Name: product_name, dtype: str,
 298    PROLEGEND® PL-T002 Universal TV Stand Table To...
 Name: product_name, dtype: str,
 144    Kodak 80 cm (32 inches) HD Ready Certified And...
 Name: product_name, dtype: str,
 48    7SEVEN® Compatible for Samsung Smart 4K Ultra ...
 Name: product_name, dtype: str,
 321    Mi 80 cm (32 inches) HD Ready Android Smart LE...
 Name: product_name, dtype: str]

In [70]:
scores[0] + 1

np.float64(1.0)

In [71]:
recomend('lg')

(1464    114
 1463    128
 1462    714
 1461     19
 1460    112
 Name: sentiment, dtype: int64,
 0       0.0
 1       0.0
 2       0.0
 3       0.0
 4       0.0
        ...
 1460    0.0
 1461    0.0
 1462    0.0
 1463    0.0
 1464    0.0
 Name: sentiment, Length: 1465, dtype: float64)

In [72]:
url  = df['img_link'][250]

In [73]:
import requests
img = requests.get(url)

In [74]:
with open("image.jpg", "wb") as f:
        f.write(img.content)

In [75]:
df['img_link'][0]

'https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51UsScvHQNL._SX300_SY300_QL70_FMwebp_.jpg'

In [76]:
def get_link(text):
    pattern = re.compile('https://m.media-amazon.com/images.*./images?')
    return pattern.sub(r'',text)

In [77]:
get_link(df['img_link'][250])

'https://m.media-amazon.com/images/I/31x9nSr-rqL._SY300_SX300_QL70_FMwebp_.jpg'

In [78]:
def get_link(text):
    match = re.search(r'.*?/images/(.+)$', text)
    if match:
        return "https://m.media-amazon.com/images/" + match.group(1)
    return text

In [79]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [80]:
vectorize = ColumnTransformer(transformers=[('vectorizer',tfidf,['product_detail'])])

In [81]:
import pickle
with open('data.pkl','wb') as f:
    pickle.dump(data,f)

In [82]:
import pickle
with open('data.pkl','wb') as f:
    pickle.dump(data,f)

In [85]:
df.drop_duplicates(subset=['product_name'])

np.int64(128)